name: cActions
version: 26.1-SNAPSHOT-2
main: ru.chipsonsky.actionssystem.ActionPlugin
description: Plugin added action system
author: chipsonsky
website: https://trident.su
api-version: '1.20.4'

commands:
  action:
    usage: "/action list|execute|devinfo <action>"
    permission: "cactions.command"